const WHATSAPP_NUMBER = '201276923493';
const PRICE = 750;
const products = [
    { id: 1, category: 't-shirts', en: 'GRAND Essential Black T-Shirt', ar: 'تيشيرت جراند الأساسي الأسود', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=85' },
    { id: 2, category: 't-shirts', en: 'GRAND Essential White T-Shirt', ar: 'تيشيرت جراند الأساسي الأبيض', image: 'https://images.unsplash.com/photo-1583743814966-8936f37f4678?auto=format&fit=crop&w=700&q=85' },
    { id: 3, category: 't-shirts', en: 'GRAND Oversized Black T-Shirt', ar: 'تيشيرت جراند أوفر سايز الأسود', image: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=700&q=85' },
    { id: 4, category: 't-shirts', en: 'GRAND Oversized White T-Shirt', ar: 'تيشيرت جراند أوفر سايز الأبيض', image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=700&q=85' },
    { id: 5, category: 'hoodies', en: 'GRAND Signature Hoodie', ar: 'هودي جراند سيجنتشر', image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=700&q=85' },
    { id: 6, category: 'hoodies', en: 'GRAND Black Hoodie', ar: 'هودي جراند الأسود', image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=700&q=85' },
    { id: 7, category: 'pants', en: 'GRAND Cargo Pants', ar: 'بنطلون جراند كارغو', image: 'https://images.unsplash.com/photo-1517438476312-10d79c077509?auto=format&fit=crop&w=700&q=85' },
    { id: 8, category: 'accessories', en: 'GRAND Essential Cap', ar: 'كاب جراند الأساسي', image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=700&q=85' }
];
const translations = {
    en: { navHome: 'Home', navShop: 'Shop', navAbout: 'About', navContact: 'Contact', whatsappShort: 'WhatsApp', heroTitle: 'WEAR YOUR', heroTitleEm: 'STATEMENT', heroDescription: 'Premium streetwear designed for those who move different.', shopNow: 'Shop now', viewCollection: 'View collection', scroll: 'SCROLL TO EXPLORE ↓', theEdit: 'THE EDIT', our: 'OUR', collection: 'COLLECTION', shopIntro: 'Sharp essentials. Considered details.<br>Made for everyday movement.', filterAll: 'All', filterTshirts: 'T-Shirts', filterHoodies: 'Hoodies', filterPants: 'Pants', filterAccessories: 'Accessories', sortBy: 'Sort by', sortFeatured: 'Featured', sortLow: 'Price: Low to high', sortHigh: 'Price: High to low', pointOfView: 'OUR POINT OF VIEW', madeToMove: 'MADE TO<br><em>MOVE.</em>', aboutText: 'GRAND is a modern streetwear brand built around confidence, simplicity and individuality.', aboutTextTwo: 'We make the pieces you reach for without thinking twice: elevated basics, relaxed silhouettes and a visual language that leaves room for you.', readStory: 'Read our story', newCollection: 'THE NEW<br><em>GRAND</em> COLLECTION', discover: 'Discover now', contactTitle: 'DIRECT LINE', contactHeading: 'TALK TO<br><em>GRAND.</em>', contactCopy: 'Questions, orders or just want to say hello? We are one message away.', contactWhatsapp: 'Contact us on WhatsApp', stayLoop: 'STAY IN THE LOOP', joinCommunity: 'JOIN THE GRAND<br><em>COMMUNITY.</em>', newsletterCopy: 'Get first access to new drops, events and more.', emailPlaceholder: 'Your email address', subscribe: 'Subscribe', copyright: '© 2026 GRAND. All rights reserved.', yourSelection: 'YOUR SELECTION', shoppingBag: 'Shopping bag', subtotal: 'Subtotal', orderCart: 'Order cart on WhatsApp', shippingNote: 'Send your selection directly to GRAND.', addToCart: 'Add to cart', orderWhatsapp: 'Order via WhatsApp', quantity: 'Quantity', remove: 'Remove', emptyCart: 'Your bag is waiting.', explore: 'Explore the collection', cartEmpty: 'Your cart is empty.', subscribed: 'You are on the list. Welcome to GRAND.', categoryEssential: 'Essential', categoryNew: 'New drop' },
    ar: { navHome: 'الرئيسية', navShop: 'المتجر', navAbout: 'عن جراند', navContact: 'تواصل معنا', whatsappShort: 'واتساب', heroTitle: 'البس', heroTitleEm: 'أسلوبك', heroDescription: 'ملابس ستريت وير عصرية ومميزة مصممة للناس المختلفة.', shopNow: 'تسوق الآن', viewCollection: 'شاهد المجموعة', scroll: 'اكتشف المجموعة ↓', theEdit: 'اختياراتنا', our: 'مجموعتنا', collection: 'الجديدة', shopIntro: 'قطع أساسية مميزة. تفاصيل مدروسة.<br>مصممة لحركتك اليومية.', filterAll: 'الكل', filterTshirts: 'تيشيرتات', filterHoodies: 'هوديز', filterPants: 'بناطيل', filterAccessories: 'إكسسوارات', sortBy: 'ترتيب حسب', sortFeatured: 'مميز', sortLow: 'السعر: من الأقل للأعلى', sortHigh: 'السعر: من الأعلى للأقل', pointOfView: 'رؤيتنا', madeToMove: 'مصممة<br><em>للحركة.</em>', aboutText: 'جراند هي علامة ملابس عصرية تهتم بالثقة والبساطة والتميز.', aboutTextTwo: 'نصمم القطع التي تختارها دون تفكير: أساسيات راقية، قصات واسعة، وهوية تترك لك مساحة لتكون أنت.', readStory: 'اكتشف قصتنا', newCollection: 'مجموعة جراند<br><em>الجديدة</em>', discover: 'اكتشف الآن', contactTitle: 'خط مباشر', contactHeading: 'تحدث مع<br><em>جراند.</em>', contactCopy: 'عندك سؤال أو طلب؟ نحن على بُعد رسالة واحدة.', contactWhatsapp: 'تواصل معنا على واتساب', stayLoop: 'كن على تواصل', joinCommunity: 'انضم إلى مجتمع<br><em>جراند.</em>', newsletterCopy: 'كن أول من يعرف عن الإصدارات والفعاليات الجديدة.', emailPlaceholder: 'بريدك الإلكتروني', subscribe: 'اشترك', copyright: '© 2026 جراند. جميع الحقوق محفوظة.', yourSelection: 'اختياراتك', shoppingBag: 'حقيبة التسوق', subtotal: 'الإجمالي', orderCart: 'اطلب السلة عبر واتساب', shippingNote: 'أرسل اختياراتك مباشرة إلى جراند.', addToCart: 'أضف إلى السلة', orderWhatsapp: 'اطلب عبر واتساب', quantity: 'الكمية', remove: 'حذف', emptyCart: 'حقيبتك تنتظرك.', explore: 'تصفح المجموعة', cartEmpty: 'سلة التسوق فارغة.', subscribed: 'تم اشتراكك. أهلاً بك في جراند.', categoryEssential: 'أساسي', categoryNew: 'إصدار جديد' }
};
let language = localStorage.getItem('grand-language') || 'en';
let activeFilter = 'all';
let cart = JSON.parse(localStorage.getItem('grand-cart') || '[]').filter(item => item && Number.isInteger(item.id)).map(item => ({ id: item.id, quantity: Math.max(1, Number(item.quantity) || 1) }));
const $ = selector => document.querySelector(selector);
const formatPrice = () => '750 EGP';
const productName = product => product[language];
function whatsappUrl(message) { return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`; }
function orderMessage(product, quantity = 1) { return language === 'ar' ? `مرحباً جراند، أريد طلب ${product.ar}، الكمية: ${quantity}، السعر: 750 EGP.` : `Hello GRAND, I want to order ${product.en}, Quantity: ${quantity}, Price: 750 EGP.`; }
function renderProducts() {
    const sort = $('#sortProducts').value;
    let visible = products.filter(product => activeFilter === 'all' || product.category === activeFilter);
    if (sort === 'low' || sort === 'high') visible = [...visible].sort((a, b) => sort === 'low' ? PRICE - PRICE : PRICE - PRICE);
    $('#productGrid').innerHTML = visible.map((product, index) => `<article class="product-card" style="animation-delay:${index * 60}ms"><div class="product-image"><img src="${product.image}" alt="${productName(product)}" loading="lazy"><span class="product-badge">${translations[language].categoryNew}</span></div><div class="product-meta"><h3>${productName(product)}</h3><p>${formatPrice()}</p></div><div class="product-actions"><label class="quantity-picker"><span>${translations[language].quantity}</span><input type="number" min="1" value="1" data-quantity="${product.id}" aria-label="${translations[language].quantity}"></label><button class="quick-add" data-add="${product.id}">${translations[language].addToCart}</button><a class="whatsapp-order" data-whatsapp="${product.id}" href="${whatsappUrl(orderMessage(product))}" target="_blank" rel="noopener">◉ ${translations[language].orderWhatsapp}</a></div></article>`).join('');
}
function renderCart() {
    const count = cart.reduce((sum, item) => sum + item.quantity, 0);
    $('#cartCount').textContent = count; $('#cartHeaderCount').textContent = `(${count})`;
    $('#cartTotal').textContent = `${(PRICE * count).toLocaleString('en-US')} EGP`;
    $('#cartItems').innerHTML = cart.length ? cart.map(item => { const product = products.find(entry => entry.id === item.id) || item; return `<div class="cart-item"><img src="${product.image}" alt="${productName(product)}"><div><h3>${productName(product)}</h3><p>${formatPrice()}</p><button class="remove-item" data-remove="${item.id}">${translations[language].remove}</button></div><div class="quantity-controls"><button data-decrease="${item.id}" aria-label="Decrease">−</button><span>${item.quantity}</span><button data-increase="${item.id}" aria-label="Increase">+</button></div></div>`; }).join('') : `<div class="empty-cart"><span>○</span><p>${translations[language].emptyCart}</p><a href="#shop" id="emptyCartLink">${translations[language].explore}</a></div>`;
    localStorage.setItem('grand-cart', JSON.stringify(cart));
}
function applyLanguage() {
    const dictionary = translations[language]; document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'; document.body.classList.toggle('arabic', language === 'ar');
    document.querySelectorAll('[data-i18n]').forEach(element => { const value = dictionary[element.dataset.i18n]; if (value !== undefined) element.innerHTML = value; });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(element => { element.placeholder = dictionary[element.dataset.i18nPlaceholder]; });
    document.querySelectorAll('.lang-button').forEach(button => button.classList.toggle('active', button.dataset.lang === language));
    $('#navWhatsapp').setAttribute('aria-label', dictionary.contactWhatsapp); $('#contactWhatsapp').href = whatsappUrl(language === 'ar' ? 'مرحباً جراند، أريد التواصل معكم.' : 'Hello GRAND, I would like to contact you.');
    renderProducts(); renderCart();
}
function addToCart(id, quantity = 1) { const existing = cart.find(item => item.id === id); if (existing) existing.quantity += quantity; else cart.push({ id, quantity }); renderCart(); openCart(); }
function openCart() { $('#cartDrawer').classList.add('open'); $('#overlay').classList.add('active'); document.body.classList.add('cart-open'); $('#cartDrawer').setAttribute('aria-hidden', 'false'); }
function closeCart() { $('#cartDrawer').classList.remove('open'); $('#overlay').classList.remove('active'); document.body.classList.remove('cart-open'); $('#cartDrawer').setAttribute('aria-hidden', 'true'); }
document.addEventListener('click', event => {
    const add = event.target.closest('[data-add]'); if (add) { const quantityInput = $(`[data-quantity="${add.dataset.add}"]`); addToCart(Number(add.dataset.add), Math.max(1, Number(quantityInput.value) || 1)); }
    const remove = event.target.closest('[data-remove]'); if (remove) { cart = cart.filter(item => item.id !== Number(remove.dataset.remove)); renderCart(); }
    const increase = event.target.closest('[data-increase]'); if (increase) { const item = cart.find(entry => entry.id === Number(increase.dataset.increase)); item.quantity += 1; renderCart(); }
    const decrease = event.target.closest('[data-decrease]'); if (decrease) { const item = cart.find(entry => entry.id === Number(decrease.dataset.decrease)); item.quantity -= 1; if (item.quantity < 1) cart = cart.filter(entry => entry.id !== item.id); renderCart(); }
    const whatsapp = event.target.closest('[data-whatsapp]'); if (whatsapp) { const product = products.find(entry => entry.id === Number(whatsapp.dataset.whatsapp)); const quantity = Number($(`[data-quantity="${product.id}"]`).value) || 1; whatsapp.href = whatsappUrl(orderMessage(product, quantity)); }
    if (event.target.id === 'emptyCartLink') closeCart();
});
document.querySelectorAll('.lang-button').forEach(button => button.addEventListener('click', () => { language = button.dataset.lang; localStorage.setItem('grand-language', language); applyLanguage(); }));
document.querySelectorAll('.filter-button').forEach(button => button.addEventListener('click', () => { $('.filter-button.active').classList.remove('active'); button.classList.add('active'); activeFilter = button.dataset.filter; renderProducts(); }));
$('#sortProducts').addEventListener('change', renderProducts); $('#cartTrigger').addEventListener('click', openCart); $('#closeCart').addEventListener('click', closeCart); $('#overlay').addEventListener('click', closeCart);
$('#checkoutButton').addEventListener('click', () => { if (!cart.length) return; const lines = cart.map(item => { const product = products.find(entry => entry.id === item.id); return `${productName(product)} x${item.quantity}`; }).join(', '); window.open(whatsappUrl(language === 'ar' ? `مرحباً جراند، أريد طلب: ${lines}. الإجمالي: 750 EGP لكل قطعة.` : `Hello GRAND, I want to order: ${lines}. Price: 750 EGP per item.`), '_blank', 'noopener'); });
const menuToggle = $('#menuToggle'); menuToggle.addEventListener('click', () => { const open = $('#navLinks').classList.toggle('open'); menuToggle.setAttribute('aria-expanded', open); });
document.querySelectorAll('.nav-links a').forEach(link => link.addEventListener('click', () => { $('#navLinks').classList.remove('open'); menuToggle.setAttribute('aria-expanded', 'false'); }));
$('#newsletterForm').addEventListener('submit', event => { event.preventDefault(); $('#formMessage').textContent = translations[language].subscribed; event.target.reset(); });
applyLanguage();